#%RAML 1.0
title: Agent Authorisation
version: 0.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]
description: An API allowing MTD-enabled Agents to request authorisation to a service for a client, instead of filling the 64-8 paper form.

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Why use this API?
   content: !include docs/why-use-this-api.md
 - title: Usage scenario
   content: !include docs/usage-scenario.md
 - title: Upcoming Feature
   content: !include docs/upcoming-feature.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:

  permissionOnAgencyRequired:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              noPermissionOnAgency:
                description: The logged in user is not permitted to access invitations for the specified agency.
                value:
                  code: NO_PERMISSION_ON_AGENCY
                  message: The account used to sign in cannot access this authorisation request. Their details do not match the agent business that created the authorisation request.

  mustBeAnAgent:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notAnAgent:
                description: The logged in user is not an agent.
                value:
                  code: NOT_AN_AGENT
                  message: This user does not have a Government Gateway agent account. They need to create an Government Gateway agent account before they can use this service.

  agentSubscriptionRequired:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              agentNotSubscribed:
                description: The Agent is not subscribed to Agent Services.
                value:
                  code: AGENT_NOT_SUBSCRIBED
                  message: This agent needs to create an agent services account before they can use this service.

  clientRegistrationRequired:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientRegistrationNotFound:
                description: The Client's registration was not found.
                value:
                  code: CLIENT_REGISTRATION_NOT_FOUND
                  message: The details provided for this client do not match HMRC's records.

  invitationMustHaveValidStatus:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invalidInvitationStatus:
                description: The requested state transition is not permitted given the invitation's current status.
                value:
                  code: INVALID_INVITATION_STATUS
                  message: This authorisation request cannot be cancelled as the client has already responded to the request, or the request has expired.

  invitationSpecified:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invitationNotFound:
                description: The specified invitation was not found.
                value:
                  code: INVITATION_NOT_FOUND
                  message: The authorisation request cannot be found.

  serviceSpecified:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                invitationNotFound:
                  description: The specified service is not supported.
                  value:
                    code: SERVICE_NOT_SUPPORTED
                    message: The service requested is not supported. Check the API documentation to find which services are supported.

  clientIdSpecified:
    responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                invalidClientId:
                  description: The submitted clientId does not match the expected format.
                  value:
                    code: CLIENT_ID_FORMAT_INVALID
                    message: Client identifier must be in the correct format. Check the API documentation to find the correct format.
                clientIdMatchesService:
                  description: The specified clientId does not match requested service.
                  value:
                    code: CLIENT_ID_DOES_NOT_MATCH_SERVICE
                    message: The type of client Identifier provided cannot be used with the requested service. Check the API documentation for details of the correct client identifiers to use.
                invalidPostcode:
                  description: The submitted postcode does not match the expected format.
                  value:
                    code: POSTCODE_FORMAT_INVALID
                    message: Postcode must be in the correct format. Check the API documentation to find the correct format.
                invalidVatRegistrationDate:
                  description: The submitted VAT registration date does not match the expected format.
                  value:
                    code: VAT_REG_DATE_FORMAT_INVALID
                    message: VAT registration date must be in the correct format. Check the API documentation to find the correct format.
#                invalidCompanyTaxUniqueTaxpayerReference:
#                  description: The submitted CT UTR does not match the expected format.
#                  value:
#                    code: CT_UTR_FORMAT_INVALID
#                    message: Corporation Tax Unique Taxpayer Reference must be in the correct format. Check the API documentation to find the correct format.

  knownFactMatches:
    responses:
        403:
          body:
            application/json:
              type: types.errorResponse
              examples:
                postcodeDoesNotMatch:
                  description: The submitted postcode did not match the client's postcode as held by HMRC.
                  value:
                    code: POSTCODE_DOES_NOT_MATCH
                    message: The submitted postcode did not match the client's postcode as held by HMRC.
                vatRegistrationDateDoesNotMatch:
                  description: The submitted VAT registration date did not match HMRC record for the client.
                  value:
                    code: VAT_REG_DATE_DOES_NOT_MATCH
                    message: The submitted VAT registration date did not match HMRC record for the client.
#                ctUtrDoesNotMatch:
#                  description: The submitted CT UTR did not match HMRC record for the client.
#                  value:
#                    code: CT_UTR_DOES_NOT_MATCH
#                    message: The submitted CT UTR did not match HMRC record for the client.

  relationshipNotFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notfoundrelationship:
                description: Relationship is inactive. Agent does not have delegated authorisation for the client.
                value:
                  code: RELATIONSHIP_NOT_FOUND
                  message: Relationship is inactive. Agent is not authorised to act for this client.

/agents/{arn}:
  /invitations:
    is: [headers.acceptHeader, mustBeAnAgent, agentSubscriptionRequired, permissionOnAgencyRequired]
    uriParameters:
      arn:
        description: The MTD platform Agent Reference Number.
        type: string
        example: AARN9999999
    post:
      is: [serviceSpecified, clientIdSpecified, clientRegistrationRequired, knownFactMatches]
      displayName: Create a new invitation
      (annotations.scope): "write:sent-invitations"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:sent-invitations" ] } ]
      body:
          application/json:
            description: Create a new authorisation request.
            type: !include schemas/create-invitation.json
            examples:
              example-1:
                value: !include examples/post-agency-invitations-example.json
              example-2:
                value: !include examples/post-agency-invitations-vat-example.json
#              example-3:
#                value: !include examples/post-agency-invitations-crn-example.json

      responses:
        204:
          description: The invitation was successfully created.
          headers:
            Location:
              example: /agents/AARN9999999/invitations/CS5AK7O8FPC43
              description: Location of the invitation that was created.

    /{invitationId}:
      is: [headers.acceptHeader, mustBeAnAgent, agentSubscriptionRequired, permissionOnAgencyRequired, invitationSpecified]
      uriParameters:
        invitationId:
          description: A unique invitation id
          type: string
          example: CS5AK7O8FPC43
      get:
        displayName: Get an invitation by id
        (annotations.scope): "read:sent-invitations"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:sent-invitations" ] } ]
        responses:
          200:
            body:
              application/json:
                description: Returns the invitation.
                type: !include schemas/invitation.json
                examples:
                  pending: !include examples/get-agency-invitation-pending-example.json
                  responded: !include examples/get-agency-invitation-responded-example.json
      delete:
        is: [invitationMustHaveValidStatus]
        displayName: Cancel an invitation by id
        (annotations.scope): "write:cancel-invitations"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:cancel-invitations" ] } ]
        responses:
          204:
            description: The invitation has been successfully cancelled

  /relationships:
    is: [headers.acceptHeader, clientRegistrationRequired, knownFactMatches, mustBeAnAgent, agentSubscriptionRequired, permissionOnAgencyRequired, relationshipNotFound, serviceSpecified, clientIdSpecified]
    uriParameters:
      arn:
        description: The MTD platform Agent Registration Number.
        type: string
        example: AARN9999999
    post:
      displayName: Get Status of a Relationship
      (annotations.scope): "read:check-relationship"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:check-relationship" ] } ]
      body:
        application/json:
          description: Check Relationship based on details received.
          type: !include schemas/create-invitation.json
          examples:
            example-1:
              value: !include examples/post-agency-invitations-example.json
            example-2:
              value: !include examples/post-agency-invitations-vat-example.json
#            example-3:
#              value: !include examples/post-agency-invitations-crn-example.json
      responses:
        204:
          description: Relationship is active. Agent has delegated authorisation for the client.
